# Generated by Django 5.2.5 on 2025-08-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='grade',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
