# Generated by Django 5.2.5 on 2025-08-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_details_grade_details_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=60)),
                ('place', models.CharField(max_length=60)),
                ('mark', models.IntegerField()),
            ],
        ),
    ]
